PTU/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    #path('feedsapi/', include('feedsapi.urls', namespace='feedsapi')),
    path('feeds/', include('feeds.urls', namespace='feeds')),
    path('', include('authenticate.urls')),
    path('forum/', include('forums.urls')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('tinymce/', include('tinymce.urls')),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('accounts/', include('allauth.urls')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('exam/', include('exams.urls')),

     # Password reset links 
     # https://github.com/django/django/blob/master/django/contrib/auth/views.py

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
                    template_name='password_reset/password_change_done.html'), 
            name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
                    template_name='password_reset/password_change.html'), 
            name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
                    template_name='password_reset/password_reset_done.html'),
            name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                    template_name='password_reset/password_change.html'), 
            name='password_reset_confirm'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(
                    template_name='password_reset/password_reset_form.html'), 
            name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
                    template_name='password_reset/password_reset_complete.html'),
            name='password_reset_complete'),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authenticate/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'authenticate'
urlpatterns = [
    path('', views.home, name="home"),
    path('signup', views.signup, name="signup"),
    path('logout', views.logoutUser, name="logout"),
    path('login', views.loginUser, name="login"),
    path('index', views.index, name="index"),
    path('activate/<uidb64>/<token>', views.activate, name="activate"),
    path('profile/<int:pk>', views.profile_view.as_view(), name="profilepage"),
    path('search/', views.account_search_view, name="search"),
    path('profile/<user_id>/edit/info', views.edit_account_view, name="edit_account")
    #path('signup', views.MakeCreate.as_view(), name='signup'),
]

dm/urls.py
from django.urls import path, re_path
from . import consumers
from . import views

app_name = 'dm'
websocket_urlpatterns = [
    re_path(r'^chat_ws$', consumers.ChatConsumer.as_asgi()),
]

urlpatterns = [
    path('messages/', views.MessagesModelList.as_view(), name='all_messages_list'),
    path('messages/<dialog_with>/', views.MessagesModelList.as_view(), name='messages_list'),
    path('dialogs/', views.DialogsModelList.as_view(), name='dialogs_list'),
    path('self/', views.SelfInfoView.as_view(), name='self_info'),
    path('upload/', views.UploadView.as_view(), name='fileupload'),
]

exams/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'exams'
urlpatterns = [
    #path('update/', views.examupdate, name="examupdate"),
    path('<slug>/', views.exam, name="exam"),
    path("<slug:exam_slug>/<slug:field_slug>/", views.exam_detail, name="exam_detail"),
    path("<slug:exam_slug>/<slug:field_slug>/<slug:year_slug>/", views.pyqs, name="pyqs"),  
]

forums/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'forums'
urlpatterns = [
    path('', views.forum, name="forum"),
    path('topic/<slug>/', views.topic, name="topic"),
    path('query/<slug>/', views.query, name="query"),
    path('new_query/', views.newquery, name="newquery"),
    path('search', views.search_results, name="search_results"),

]

exams/models.py
from re import T
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE, SET_NULL
from django.db.models.fields import related
from django.db.models.fields.related import ForeignKey
from django.utils.text import slugify
from tinymce.models import HTMLField
from django.shortcuts import reverse

class Exam(models.Model):
    exam = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True, blank=True)

    def __str__(self):
        return self.exam
    
    def get_url(self):
        return reverse("exams:exam", kwargs={
            "slug": self.slug
        })

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.exam)
        super(Exam, self).save(*args, **kwargs)

        

class Exam_Detail(models.Model):
    exam = models.ForeignKey('Exam', on_delete=models.CASCADE, null=True)
    field = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    reg_link = models.URLField(blank=True)
    exam_content = models.CharField(max_length=10000000, blank=True)
    important_dates = HTMLField(blank=True)
    syllabus = models.CharField(blank=True, max_length=150)

    def __str__(self):
        return self.field

    def get_url(self):
        return reverse("exams:exam_detail", kwargs={
            "exam_slug": self.exam.slug,
            "field_slug": self.slug,
        })


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.field)
        super(Exam_Detail, self).save(*args, **kwargs)



class Pyqs(models.Model):
    exam = models.ForeignKey('Exam', on_delete=models.CASCADE)
    exam_field = models.ForeignKey('Exam_Detail', on_delete=models.CASCADE)
    phase = models.CharField(max_length=300, blank=True, null=True)
    year = models.IntegerField(null=True)
    year_slug = models.SlugField(max_length=4)
    category = models.CharField(max_length=300, blank=True, null=True)
    subject = models.CharField(max_length=100)
    question_link = models.URLField()
    answer_link = models.URLField(blank=True, null=True)

    def get_url(self):
        return reverse("exams:pyqs", kwargs={
            "exam_slug": self.exam.slug,
            "field_slug": self.exam_field.slug,
            "year_slug": self.year_slug
        })

    def save(self, *args, **kwargs):
        if not self.year_slug:
            self.year_slug = slugify(self.year)
        super(Pyqs, self).save(*args, **kwargs)

    def __str__(self):
        if self.phase is not None:
            return self.phase
        else:
            return self.subject
    
class Gate_Syllabus(models.Model):
    year = models.IntegerField(null=True)
    gate_paper = models.CharField(max_length=100)
    syllabus = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.gate_paper
        

exams/views.py
from django.db.models import fields
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from .models import Exam, Exam_Detail, Gate_Syllabus, Pyqs
#from . import data

def exam(request, slug):
    exam = get_object_or_404(Exam, slug=slug)
    print(exam)
    fields = Exam_Detail.objects.filter(exam = exam)
    if slug == 'gate' :
        syllabus = Gate_Syllabus.objects.all().values()
    elif slug == 'cat':
        return redirect("exams:exam_detail", exam_slug = slug, field_slug = slug)
    else:
        syllabus = None
    context = {'fields': fields, 'exam': exam, 'gate_syllabus': syllabus}
    return render (request, 'exams/exam.html', context)


'''
def examupdate(request):
    update = data.GATE.gatesyl()
    return redirect('http://127.0.0.1:8000/admin/exams')'''
    



def exam_detail(request, exam_slug, field_slug):
    exams = [c.slug for c in Exam.objects.all()]
    if exam_slug in exams:
        exam_match = Exam.objects.get(slug = exam_slug)
        fields = [k.slug for k in Exam_Detail.objects.filter(exam = exam_match)]
        if field_slug in fields:
            field_match = Exam_Detail.objects.filter(slug = field_slug).values_list('id','field')
            field = get_object_or_404(Exam_Detail, slug=field_slug)
            field_content = field.exam_content
            #print(field.exam_content)
            pyq = list(Pyqs.objects.filter(exam_field = field).values('year', 'year_slug'))
            for k in pyq:
                c = k
                for p in pyq[pyq.index(k)+1:]:
                    if p == c:
                        pyq.remove(p)
            #print(pyq, len(pyq)) 
            context = {
                'field_match': field_match,
                'field_content': field_content, 
                'field': field,
                'pyqs': pyq,
                'path': 'templates/exams/upsc/ifs.html',
            }
            return render (request, 'exams/exam_detail.html', context)
        else:
            return redirect("http://127.0.0.1:8000/")
    return redirect("http://127.0.0.1:8000/")




def pyqs(request, exam_slug, field_slug, year_slug):
    objs = Pyqs.objects.filter(exam = Exam.objects.get(slug = exam_slug).id, exam_field = Exam_Detail.objects.get(slug=field_slug).id, year_slug = year_slug ).values('phase')
    obj = list(objs)
    for k in obj:
                c = k
                for p in obj[obj.index(k)+1:]:
                    if p == c:
                        obj.remove(p)
    #print(obj, len(obj))
    cag = []
    for k in obj:
        catg = objs.filter(phase = k['phase'])
        cat = list((catg).values('category', 'subject', 'question_link', 'answer_link'))
        #print(cat, len(cat))
        cag.append(cat)
    zip_obj = zip(obj, cag)
    context = {
        'objects': obj,
        'category': zip_obj,
        'year': year_slug
        }
    return render (request, 'exams/pyqs.html', context)
    

templates/exams/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>MyPTU - Exams</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--<link rel="stylesheet" href="{% static '/css/forumstyle.css' %}">-->
        <link rel="stylesheet" href="{% static '/css/index.css' %}">
        <link rel="stylesheet" href="{% static '/css/base.css' %}">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!-- Including the bootstrap CDN -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    </head>
    <body>
        <style>
            .logo{
                font-size: 20px !important; 
                font-family: "Roboto", Arial, Helvetica, sans-serif !important;
                font-weight: bolder;
                letter-spacing: 1.5px;
                color: var(--color-theme-blue) !important;
            }
            .nav-link{
                color: var(--color-nav-link-grey) !important;
                font-weight: bold;
            }
            .nav-link:hover{
                color: var(--color-theme-blue) !important;
                transform: scale(1.03);
            }

            .nav-link.active {
                color: #0080FF;
            }

            @media screen and (max-width: 460px){
                .form-control{
                    display: none;
                }
            }

        </style>

        <div class="head">         
            <nav class="navbar navbar-expand-lg navbar-light" >
                <div class="container-fluid">
                    <a class="navbar-brand logo" href="">MyPTU <span style="color:var(--color-nav-link-grey)">Exams</span></a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ml-auto" style="color: var(--color-nav-link-grey)">
                        <li class="nav-item nav-lnk">
                            <a class="nav-link" href="{% url 'authenticate:home' %}">Home</a>
                            </li>
                        <li class="nav-item nav-lnk">
                            <a class="nav-link" href="{% url 'forums:forum' %}">Categories</a>
                        </li>
                        <li class="nav-item nav-lnk">
                            <a class="nav-link" href="{% url 'authenticate:profilepage' request.user.id %}">Profile</a>
                        </li>
                        <li class="nav-item nav-lnk">
                            {% if request.user.is_authenticated %}
                                <a class="nav-link" aria-current="page" href="{% url 'authenticate:logout' %}" method="POST">Logout</a>
                            {% else %}
                                <a class="nav-link" aria-current="page" href="{% url 'authenticate:login' %}?next={{ request.path }}" method="POST">Login</a>
                            {% endif %}
                        </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <!--Search Box
        <div class="search-box">

        <form action="#" method="GET">
            <div class="col-5 input-group mb-3 mx-auto">
                <input type="text" class="form-control" name="keyword" id="" placeholder="Search">
                <div class=" col-3 input-group-append ">
                    <button type="submit" name="search-sub"><i class="material-icons">search</i></button>
                    <input type="text"  class="res-search" name="keyword-mob" id="" placeholder="Search">
                </div>
            </div>
        </form>
    -->
        </div>

        <div class="container" >
            <div class="row">
                <div class="col-2">
                    <nav class="nav flex-column bd-links border-right">
                        <a class="nav-link active" aria-current="page" href="{% url 'exams:exam' 'upsc' %}">UPSC</a>
                        <a class="nav-link" href="{% url 'exams:exam' 'cat' %}">CAT</a>
                        <a class="nav-link" href="{% url 'exams:exam' 'gate' %}">GATE</a>
                    </nav>
                </div>
                <div class="col-8">
                    {% block content %}
        
                    {% endblock content %}
                </div>
            </div>
        </div>



        <div class="basefoot">
        
        </div>
        
        <script src="{% static '/js/forum.js' %}" async defer></script>
    </body>
</html>

templates/exams/exam.html
{% extends "exams/base.html" %}

{% block content %}

    <div class="tab-content" id="v-nav-tab">
    <div class="tab-pane fade show active" role="tabpanel" aria-labelledby="v-nav-upsc-tab">
        {% for field in fields %}
        <div class=" p-3 mb-2 bg-light border text-white rounded shadow-sm">
            <div class="col-sm">
                <a href="{{field.get_url}}">{{field}}</a>
            </div>
        </div>
        {% endfor %}
        <br>
        {% if gate_syllabus is not None %}
            <table>
                <thead>
                    <tr>
                        <td>Field</td>
                        <td>Syllabus</td>
                    </tr>
                </thead>
                <tbody>
                    {% for s in gate_syllabus %}
                        <tr>
                            <td>{{s.gate_paper}}</td>
                            <td><a href='{{s.syllabus}}'>Click Here</a></td>
                        </tr>
                    {% endfor %}
            </tbody>
            </table>
        {% endif %}
    </div>
    <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">...</div>
    <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">...</div>
    <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">...</div>
    </div>
        
{% endblock content %}

templates/exams/exam_detail.html
{% extends "exams/base.html" %}


{% block content %}

        
            <h1>{{ field }}</h1><br><br>
            {% if field_content is not None %}
            <div>
            {% autoescape off %}
                {{field_content|safe}}
            {% endautoescape %}
            </div>
            {% endif %}
            
            <h3>Previos Years Question Papers</h3><br>
                {% for k in pyqs %}
                    <h1><a href = "{% url 'exams:pyqs' exam_slug=field.exam.slug field_slug=field.slug year_slug=k.year_slug %}">{{k.year}}</a></h1>
                {% endfor %}

{% endblock content %}

templates/exams/pyqs.html
{% extends "exams/base.html" %}

{% block content %}
    <h2>Previos Years Question Papers: Year {{year}}</h2><br>
        {% for k, l in category %}
            <br>
            {% if k.phase is not None %}
                <h3>{{k.phase}}</h3>
            {% endif %}
            <table>
                <tbody>
                {% for c in l %}
                    {% if c.category is not None %}
                        <tr>
                            <td>{{c.category}}</td> 
                            <td>{{c.subject}}</td>  
                            <td><a href="{{c.question_link}}">Click Here</a></td>
                        </tr>
                    {% else %}   
                        {% if c.answer_link is not None %}
                            <tr>
                                <td>{{c.subject}}</td>  
                                <td><a href="{{c.question_link}}">Click Here</a></td>
                                <td><a href="{{c.answer_link}}">Answer Key</a></td>
                            </tr>
                            
                        {% else %}
                            <tr>
                                <td>{{c.subject}}</td>  
                                <td><a href="{{c.question_link}}">Click Here</a></td>
                            </tr>
                        {% endif %}
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        {% endfor %}
        

{% endblock content %}