PTU/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    #path('feedsapi/', include('feedsapi.urls', namespace='feedsapi')),
    path('feeds/', include('feeds.urls', namespace='feeds')),
    path('', include('authenticate.urls')),
    path('forum/', include('forums.urls')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('tinymce/', include('tinymce.urls')),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('accounts/', include('allauth.urls')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('exam/', include('exams.urls')),

     # Password reset links 
     # https://github.com/django/django/blob/master/django/contrib/auth/views.py

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
                    template_name='password_reset/password_change_done.html'), 
            name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
                    template_name='password_reset/password_change.html'), 
            name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
                    template_name='password_reset/password_reset_done.html'),
            name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                    template_name='password_reset/password_change.html'), 
            name='password_reset_confirm'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(
                    template_name='password_reset/password_reset_form.html'), 
            name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
                    template_name='password_reset/password_reset_complete.html'),
            name='password_reset_complete'),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authenticate/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'authenticate'
urlpatterns = [
    path('', views.home, name="home"),
    path('signup', views.signup, name="signup"),
    path('logout', views.logoutUser, name="logout"),
    path('login', views.loginUser, name="login"),
    path('index', views.index, name="index"),
    path('activate/<uidb64>/<token>', views.activate, name="activate"),
    path('profile/<int:pk>', views.profile_view.as_view(), name="profilepage"),
    path('search/', views.account_search_view, name="search"),
    path('profile/<user_id>/edit/info', views.edit_account_view, name="edit_account")
    #path('signup', views.MakeCreate.as_view(), name='signup'),
]

dm/urls.py
from django.urls import path, re_path
from . import consumers
from . import views

app_name = 'dm'
websocket_urlpatterns = [
    re_path(r'^chat_ws$', consumers.ChatConsumer.as_asgi()),
]

urlpatterns = [
    path('messages/', views.MessagesModelList.as_view(), name='all_messages_list'),
    path('messages/<dialog_with>/', views.MessagesModelList.as_view(), name='messages_list'),
    path('dialogs/', views.DialogsModelList.as_view(), name='dialogs_list'),
    path('self/', views.SelfInfoView.as_view(), name='self_info'),
    path('upload/', views.UploadView.as_view(), name='fileupload'),
]

workshops/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'workshops'

urlpatterns = [
    #path('<slug>/', views.CategoryView, name = 'category'),
    path('',views.ListView, name = 'workshop-list'),
    path('<slug>/',views.WorkshopView,name="workshop")

]

workshops/models.py
from django.conf import Settings
from django.db import models
from django.db.models.fields.related import ForeignKey
from django.conf import settings
from django.shortcuts import reverse
from django.utils.text import slugify

# Create your models here.
class Workshop(models.Model):
    workshop_title = models.CharField(max_length = 100)
    description=models.TextField()
    slug = models.SlugField(max_length=50,unique=True,blank=True)
    category = models.CharField(max_length = 100)
    date = models.TextField()
    price = models.TextField()

    def __str__(self):
        return self.workshop_title
    def get_url(self):
        return reverse("workshop:workshop_title", kwargs={
            "slug" : self.slug
        })
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.workshop_title)
        super(Workshop, self).save(*args, **kwargs)
    

class Registered_workshop(models.Model):
    userid = models.ForeignKey(settings.AUTH_USER_MODEL,related_name = 'registered_user',on_delete = models.CASCADE,null = True)
    workshop_id = models.ForeignKey(Workshop,on_delete=models.CASCADE)
    date_time = models.DateTimeField()
    expiry = models.BooleanField()

workshops/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http.response import HttpResponse
from django.core.paginator import Paginator
from .models import Workshop,Registered_workshop

# Create your views here.

def ListView(request):
    #workshop = get_object_or_404(Workshop,id=1)
    workshop_list = Workshop.objects.all()
    paginator = Paginator(workshop_list, 20)
    page = request.GET.get('page')
    #page = int(page)
    #print(type(page))
    #print(page)
    page_obj = Paginator.get_page(paginator,page)
    return render(request,'workshops/list_workshop.html',{'page_obj':page_obj})

def WorkshopView(request,slug):
    workshops = get_object_or_404(Workshop,slug=slug)
    return render(request,'workshops/workshop.html',{'workshops':workshops})

templates/workshops/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>MyPTU - Events</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static '/css/forumstyle.css' %}">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>
    <body>
        <div class="head">         
            <div class="navbar">
                <nav class="forum-nav">
                    <ul class="logo">
                        <li>MyPTU <span style="color:#5f6368">Exams</span></li>
                    </ul>
                    <div class="res-nav">
                        <div class="l1"></div>
                        <div class="l2"></div>
                        <div class="l3"></div>
                    </div>
                    <ul class="nav-list">
                        <li class="nav-lnk">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'authenticate:logout' %}" method="POST">Logout</a>
                        {% else %}
                            <a href="{% url 'authenticate:login' %}?next={{ request.path }}" method="POST">Login</a>
                        {% endif %}
                        </li>
                        <li class="nav-lnk">
                            <a href="{% url 'workshops:workshop-list' %}">Workshops</a>
                        </li>
                        <li class="nav-lnk">
                            <a href="{% url 'authenticate:profilepage' request.user.id %}">Profile</a>
                        </li>
                        <li class="nav-lnk">
                            <a href="{% url 'authenticate:home' %}">Home</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <!--Search Box-->
        <div class="search-box">

        <form action="#" method="GET">
    
            <select name="search-box" id="">
                <option value="title">Title</option>
                <option value="category">Category</option>
            </select>
            <input type="text"  class="main-search" name="keyword" id="" placeholder="Search">
            <div class="search-but">
                <button type="submit" name="search-sub"><i class="material-icons">search</i></button>
                <input type="text"  class="res-search" name="keyword-mob" id="" placeholder="Search">
            </div>
        </form>

        </div>

        {% block content %}
        
        {% endblock content %}


        <div class="footer">
        
        </div>
        
        <script src="{% static '/js/forum.js' %}" async defer></script>
    </body>
</html>

templates/workshops/list_workshop.html
{% extends "workshops/base.html" %}

{% block content %}
    
        <div>
            {% for obj in page_obj %}
            <a href="{% url 'workshops:workshop' slug=obj.slug %}">
                {{obj.workshop_title}}
            </a> - {{ obj.category }}<br><br>
            {% endfor %}
        </div>
        <div>
            {% if page_obj.has_previous %}
                <a href="?page={{page_obj.previous_page_number}}">Previous</a>
            {% endif %}
        </div>
        <div>
            {% if page_obj.has_next %}
                <a href="?page={{page_obj.next_page_number}}">Next</a>
            {% endif %}
        </div>

{% endblock content %}

templates/workshops/workshop.html
{% extends "workshops/base.html" %}

{% block content %}

        <title>
            {{workshops.workshop_title}}
        </title>

        <div>
            {{workshops.workshop_title}}
        </div>
        <br>
        <div>
            Description: <br>
            {{workshops.description | safe}}
        </div>
        <br>
        <div>
            {% if Date %}
                Date:{{workshops.date}}
            {% endif %}
        </div>
        <br>
        <div>
            Price:{{workshops.price}}
        </div>

{% endblock content %}