PTU/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    #path('feedsapi/', include('feedsapi.urls', namespace='feedsapi')),
    path('feeds/', include('feeds.urls', namespace='feeds')),
    path('', include('authenticate.urls')),
    path('forum/', include('forums.urls')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('tinymce/', include('tinymce.urls')),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('accounts/', include('allauth.urls')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('exam/', include('exams.urls')),

     # Password reset links 
     # https://github.com/django/django/blob/master/django/contrib/auth/views.py

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
                    template_name='password_reset/password_change_done.html'), 
            name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
                    template_name='password_reset/password_change.html'), 
            name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
                    template_name='password_reset/password_reset_done.html'),
            name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                    template_name='password_reset/password_change.html'), 
            name='password_reset_confirm'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(
                    template_name='password_reset/password_reset_form.html'), 
            name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
                    template_name='password_reset/password_reset_complete.html'),
            name='password_reset_complete'),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='chatindex'),
    path('<slug:room_name>/', views.room, name='room'),
]

dm/urls.py
from django.urls import path, re_path
from . import consumers
from . import views

app_name = 'dm'
websocket_urlpatterns = [
    re_path(r'^chat_ws$', consumers.ChatConsumer.as_asgi()),
]

urlpatterns = [
    path('messages/', views.MessagesModelList.as_view(), name='all_messages_list'),
    path('messages/<dialog_with>/', views.MessagesModelList.as_view(), name='messages_list'),
    path('dialogs/', views.DialogsModelList.as_view(), name='dialogs_list'),
    path('self/', views.SelfInfoView.as_view(), name='self_info'),
    path('upload/', views.UploadView.as_view(), name='fileupload'),
]

chat/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.fields import related
from django.conf import settings


class Rooms(models.Model):
    room = models.CharField(null=True, max_length=30, default='test')
    user_created = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='room_author', on_delete=models.CASCADE, null=True)
    channel_name = models.TextField(null=True)

    def __str__(self):
        return self.room

class Message(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='message_author', on_delete=models.CASCADE)
    room = models.ForeignKey(Rooms, on_delete=models.CASCADE)
    msg_content = models.TextField()
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.author.username

    def last_20_messages():
        return Message.objects.order_by('-time').all()[:20]

chat/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

from .models import Message, Rooms




def index(request):
    context = {}
    rooms = Rooms.objects.all()
    context['rooms'] = rooms
    return render(request, 'chat/index.html', context)

@login_required
def room(request, room_name):
    room = Rooms.objects.filter(room = room_name).first()
    chats = []
    if room:
        chats = Message.objects.filter(room = room)
    else:
        room = Rooms(room = room_name)
        room.save()
        
    return render(request, 'chat/room.html', {
        'room_name': room_name,
        'chats': chats,
        #'username': request.user.username
    })
    

templates/chat/index.html
<!-- templates/chat/index.html   window.location.pathname = 'chat/' + roomName + '/';-->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">
    {% for room in rooms %}
    <ul>
        <li><a href="{% url 'chat:room' room.room %}">{{room.room}}</a></li>
    </ul>
    {% endfor %}
    

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = 'chat/' + roomName + '/';
        };
    </script>
</body>
</html>

templates/chat/room.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20">
        {% for chat in chats.all  %}
            {% if chat.author.id == request.user.id %}
                <p style="color:blue;">{{chat.author}}: {{ chat.msg_content }}</p>
            {% else %}
                <p>{{chat.author}}: {{ chat.msg_content }}</p>
            {% endif %}
        {% endfor %}
    </textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    <p>{{ room_name|json_script:"room-name" }}</p>
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            console.log(data);
            document.querySelector('#chat-log').value += (data.username + ': ' +data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
            }));
            messageInputDom.value = '';
        };
    </script>
</body>
</html>

templates/chat/room02.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}
    {{ username|json_script:"user-name" }}

    <script src="{% static 'js/reconnecting-websocket.js' %}"></script>
    
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);
        var username = JSON.parse(document.getElementById('user-name').textContent);

        const chatSocket = new ReconnectingWebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            var message = data['message'];
            var author = message['author'];

            var msgListTag = document.createElement('li');
            var imgTag = document.createElement('img');
            var pTag = document.createElement('p');
            pTag.textContent = message.content;
            imgTag.src = 'http://emilcarlsson.se/assets/mikeross.png';

            if (author === username){
                msgListTag.className = 'sent';
            }
            else{
                msgListTag.className = 'replies';
            }

            msgListTag.appendChild(imgTag);
            msgListTag.appendChild(pTag);

            document.querySelector('#chat-log').appendChild(msgListTag);
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
                'command': 'new_messages',
                'from': username
            }));
            messageInputDom.value = '';
        };
    </script>
</body>
</html>