PTU/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    #path('feedsapi/', include('feedsapi.urls', namespace='feedsapi')),
    path('feeds/', include('feeds.urls', namespace='feeds')),
    path('', include('authenticate.urls')),
    path('forum/', include('forums.urls')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('tinymce/', include('tinymce.urls')),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('accounts/', include('allauth.urls')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('exam/', include('exams.urls')),

     # Password reset links 
     # https://github.com/django/django/blob/master/django/contrib/auth/views.py

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
                    template_name='password_reset/password_change_done.html'), 
            name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
                    template_name='password_reset/password_change.html'), 
            name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
                    template_name='password_reset/password_reset_done.html'),
            name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                    template_name='password_reset/password_change.html'), 
            name='password_reset_confirm'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(
                    template_name='password_reset/password_reset_form.html'), 
            name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
                    template_name='password_reset/password_reset_complete.html'),
            name='password_reset_complete'),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authenticate/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'authenticate'
urlpatterns = [
    path('', views.home, name="home"),
    path('signup', views.signup, name="signup"),
    path('logout', views.logoutUser, name="logout"),
    path('login', views.loginUser, name="login"),
    path('index', views.index, name="index"),
    path('activate/<uidb64>/<token>', views.activate, name="activate"),
    path('profile/<int:pk>', views.profile_view.as_view(), name="profilepage"),
    path('search/', views.account_search_view, name="search"),
    path('profile/<user_id>/edit/info', views.edit_account_view, name="edit_account")
    #path('signup', views.MakeCreate.as_view(), name='signup'),
]

dm/urls.py
from django.urls import path, re_path
from . import consumers
from . import views

app_name = 'dm'
websocket_urlpatterns = [
    re_path(r'^chat_ws$', consumers.ChatConsumer.as_asgi()),
]

urlpatterns = [
    path('messages/', views.MessagesModelList.as_view(), name='all_messages_list'),
    path('messages/<dialog_with>/', views.MessagesModelList.as_view(), name='messages_list'),
    path('dialogs/', views.DialogsModelList.as_view(), name='dialogs_list'),
    path('self/', views.SelfInfoView.as_view(), name='self_info'),
    path('upload/', views.UploadView.as_view(), name='fileupload'),
]

forums/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'forums'
urlpatterns = [
    path('', views.forum, name="forum"),
    path('topic/<slug>/', views.topic, name="topic"),
    path('query/<slug>/', views.query, name="query"),
    path('new_query/', views.newquery, name="newquery"),
    path('search', views.search_results, name="search_results"),

]

forums/models.py
from django.db import models
from django.db.models.deletion import CASCADE, SET_NULL
from django.db.models.fields import related
from django.db.models.fields.related import ForeignKey
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.contrib.contenttypes.fields import GenericRelation
from django.shortcuts import reverse
from django.conf import settings

from ckeditor.fields import RichTextField
from tinymce.models import HTMLField
from taggit.managers import TaggableManager
from hitcount.models import HitCountMixin, HitCount

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=400, unique=True, blank=True)

    class Meta:
        verbose_name_plural = 'categories'
    def __str__(self) :
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)

    def get_url(self):
        return reverse("forums:topic", kwargs={
            "slug": self.slug
        })

    @property
    def num_queries(self):
        return Query.objects.filter(categories = self).count()

    @property
    def last_query(self):
        return Query.objects.filter(categories = self).latest("date")


class Reply(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    reply = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'replies'
    
    def __str__(self) :
        return self.reply[:150]


class Query(models.Model):
    title = models.CharField(max_length=400)
    slug = models.SlugField(max_length=400, unique=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    content = RichTextField(blank=True, null=True)
    #content = models.TextField()
    categories = models.ManyToManyField(Category)
    date = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
            related_query_name = 'hit_count_generic_relation'
    )
    tags = TaggableManager()
    replies = models.ManyToManyField(Reply, blank=True) 

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Query, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_url(self):
        return reverse("forums:query", kwargs={
            "slug": self.slug
        })

    @property
    def num_rply(self):
        return self.replies.count()

forums/forms.py
from django import forms
from django.db.models import fields
from django.forms import models
from .models import Query

class NewQuery(forms.ModelForm):
    class Meta:
        model = Query
        fields = ["title", "content", "categories", "tags"]

forums/views.py
from decimal import Context
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.conf import settings

from authenticate.models import Account
from .models import Category, Query, Reply
from . utils import update_views
from .forms import NewQuery
# Create your views here.

def forum(request):
    topics = Category.objects.all()
    paginator = Paginator(topics, 3)
    page = request.GET.get("page")
    try:
        topics = paginator.page(page)
    except PageNotAnInteger:
        topics = paginator.page(1)
    except EmptyPage:
        topics = paginator.page(paginator.num_pages)
    context = {
        "topics":topics,
    }
    return render(request, "forums/forum.html", context)

def topic(request, slug):
    category = get_object_or_404(Category, slug=slug)
    queries = Query.objects.filter(approved=True, categories=category)
    paginator = Paginator(queries, 5)
    page = request.GET.get("page")
    try:
        queries = paginator.page(page)
    except PageNotAnInteger:
        queries = paginator.page(1)
    except EmptyPage:
        queries = paginator.page(paginator.num_pages)

    context = {
        "topic_queries":queries,
        "catgr": category,
    }
    return render(request, "forums/forum_posts.html", context)

    
@login_required(login_url="authenticate:login")
def query(request, slug):
    question = get_object_or_404(Query, slug=slug)
    r_user = Account.objects.get(username = request.user.username)
    print("rply start! \n")

    if "submit_reply" in request.POST:
        rply = request.POST.get("reply")
        print("rely: ", rply, "\n")
        new_reply, created = Reply.objects.get_or_create(user=r_user, reply=rply)
        question.replies.add(new_reply.id)


    context = {
        "query":question
    }
    update_views(request, question)
    return render(request, "forums/post_detail.html", context)


@login_required(login_url="authenticate:login")
def newquery(request):
    context = {}
    form = NewQuery(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            q_user = Account.objects.get(username = request.user.username)
            new_query = form.save(commit=False)
            new_query.user = q_user
            new_query.save()
            return redirect("forums:forum")
    context.update({
        "form": form,
        "title": "New Query"
    })
    return render(request, "forums/new_query.html", context)


def search_results(request):
    context = {}
    
    
    if "search-sub" in request.GET:
        keyword = request.GET.get("keyword")
        #filter starting
        
        search_box = request.GET.get("search-box")
        if search_box == "title":
            results = Query.objects.all()
            objects = Query.objects.filter(title__contains = keyword)
           
        elif search_box == "category":
            results = Category.objects.all()
            objects = Category.objects.filter(title__contains = keyword)
        

        #ends
        paginator = Paginator(objects, 1)
        page = request.GET.get("page")
        try:
            results = paginator.page(page)
        except PageNotAnInteger:
            results = paginator.page(1)
        except EmptyPage:
            results = paginator.page(paginator.num_pages)
        


        print("\n\n")
        print(keyword)
        for obj in objects:
            print(obj)

        context = {
            "objects": objects,
            "searched": keyword,
            "search_box":search_box,
            "results":results,
        }
    return render(request, "forums/search.html", context)

templates/forums/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>MyPTU-Forum</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static '/css/forumstyle.css' %}">
        <link rel="stylesheet" href="{% static '/css/index.css' %}">
        <link rel="stylesheet" href="{% static '/css/base.css' %}">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>
    <body>
        <div class="head">         
            <div class="navbar">
                <nav class="forum-nav">
                    <ul class="logo">
                        <li>MyPTU <span style="color:#5f6368">Forum</span></li>
                    </ul>
                    <div class="res-nav">
                        <div class="l1"></div>
                        <div class="l2"></div>
                        <div class="l3"></div>
                    </div>
                    <ul class="nav-list">
                        <li class="nav-lnk">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'authenticate:logout' %}" method="POST">Logout</a>
                        {% else %}
                            <a href="{% url 'authenticate:login' %}?next={{ request.path }}" method="POST">Login</a>
                        {% endif %}
                        </li>
                        <li class="nav-lnk">
                            <a href="{% url 'forums:forum' %}">Categories</a>
                        </li>
                        <li class="nav-lnk">
                            <a href="#">Profile</a>
                        </li>
                        <li class="nav-lnk">
                            <a href="{% url 'authenticate:home' %}">Home</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <!--Search Box-->
        <div class="search-box">

        <form action="{% url 'forums:search_results' %}" method="GET">
    
            <select name="search-box" id="">
                <option value="title">Title</option>
                <option value="category">Category</option>
            </select>
            <input type="text"  class="main-search" name="keyword" id="" placeholder="Search">
            <div class="search-but">
                <button type="submit" name="search-sub"><i class="material-icons">search</i></button>
                <input type="text"  class="res-search" name="keyword-mob" id="" placeholder="Search">
            </div>
        </form>

            <div class="postquery">
                <button type="button"><a href="{% url 'forums:newquery' %}" style="color:#fff;"><i class="material-icons">add</i><span>New Query</span></a></button>
            </div>
        </div>

        {% block content %}
        
        {% endblock content %}


        <div class="footer">
        
        </div>
        
        <script src="{% static '/js/forum.js' %}" async defer></script>
    </body>
</html>

templates/forums/forum.html
{% extends "forums/base.html" %}

{% block content %}

        <div class="conatainer">
            <div class="subforum">
                <div class="subforum-title">
                    <h1> Categories</h1>
                </div>

                {% for topic in topics  %}     
 
                <div class="subforum-row">
                    <div class="subforum-icon subforum-col col-centre">
                        <i class="material-icons">
                                person
                        </i>
                    </div>
                    <div class="subforum-des subforum-col">
                        <h1><a href="{{ topic.get_url }}">
                        <p> {{topic.title}}</p></a></h1>
                    </div>
                    <div class="subforum-stats subforum-col col-centre">
                        <span>{{ topic.num_queries }} Queries</span>
                    </div>
                    <div class="subforum-info subforum-col">
                        <b><a href="{{topic.last_query.get_url}}">Last Query</a></b> on {{ topic.last_query.date | date }}
                    </div>
                </div>
                {% endfor %}


            </div>
            <hr class="row-division">
        </div>
        <!--Pagination-->
            <div class="pagination">
                Page: {% for num_page in topics.paginator.page_range %} <a href="?page={{num_page}}">{{ num_page }}</a>{% endfor %}
            
            </div>
    {% endblock content %}

templates/forums/forum_posts.html
{% extends "forums/base.html" %}
{% load hitcount_tags %}
{% block content %}
        <div class="conatainer">
            <div class="dir">
                <span><a href="{% url 'forums:forum' %}">Forum</a> >> <a href="{{ catgr.get_url }}">{{ catgr.title }}</a></span>
            </div>
            <div class="post-table">
                <div class="table-head">
                    <div class="prof-pic">User</div>
                    <div class="subject">Subject</div>
                    <div class="replies">Views<span>/ Replies</span></div>
                    <div class="posted-on">Posted On</div>
                </div>

                {% for post in topic_queries  %}             
                <div class="table-row">
                    <div class="prof-pic"><i class="material-icons">person</i></div>
                    <div class="subject"><a href="{{ post.get_url }}">{{ post.title }}</a>
                        <br>
                        <br>
                        <span> Posted by <b><a href="#">{{ post.user.username }}</a></b></span>
                    </div>
                    <div class="replies">{{ post.num_rply }} replies | {% get_hit_count for post %} views</div>
                    <div class="posted-on">{{ post.date | date }}</div>
                </div>
                {% endfor %}

            </div>
            <!--Pagination-->
            <div class="pagination">
                Page: {% for num_page in topic_queries.paginator.page_range %} <a href="?page={{num_page}}">{{ num_page }}</a>{% endfor %}
            
            </div>
        </div>
 {% endblock content %}

templates/forums/new_query.html
{% extends "forums/base.html" %}
{% load crispy_forms_tags %}


{% block content %}

<style>

.postquery button{
    display:none;
}

</style>

    <h1 class="make-q" > Hello <span style="color: #1a73e8;">{{user}}</span>,  <span style="font-size: 18px;">make your query:</span></h1>
    <div  class="newq-form">
    <form method="POST" enctype="multipar/form-data">
    {% csrf_token %}
        {{ form.media }}
        {{ form | crispy }}
        <div class="post-sub-butn">
        <input type="submit" value="Post Query" class="post-sub">
        </div>
    </form>
    </div>

{% endblock content %}

templates/forums/post_detail.html
{% extends "forums/base.html" %}
{% load hitcount_tags %}
{% load forum_extras %}
{% block content %}
        <div class="conatainer">
            <div class="dir">
                <span><a href="{% url 'forums:forum' %}">Forum</a> >> <a href="{{ query.categories.all.0.get_url }}">{{ query.categories.all.0 }}</a> >> <a href="{{ query.get_url }}">{{ query.title }}</a></span>
            </div>
            <div class="topic">
                <div class="topic-head">
                    <div class="postuser">User</div>
                    <div class="content">{{ query.title }}</div>
                </div>
                <div class="topic-body">
                    <div class="postuser">
                        <div class="user-img">
                            <img src="https://cdn.pixabay.com/photo/2014/04/03/10/32/user-310807_960_720.png">
                        </div>
                        <div class="user-detail">
                            <div class="username"><a href="#">{{ query.user.username }}</a></div>
                            <div><em>Views: {% get_hit_count for query %}</em></div>
                            <div><em>Points: 200</em></div>
                        </div>
                    </div>
                    <div class="content">
                        {{ query.content| convert_markdown | safe }}
                    </div>
                </div>
                <div class = "rply-btn-area">
                    <div class="rply-btn">
                        <button type="button" onclick="showReply()">Reply</button>
                    </div>
                    <div class="rply-btn">
                        <button type="button" onclick="showReplies()">View Replies</button>
                    </div>
                </div>
            </div>
            <form action='.' method='POST'>
            {% csrf_token %}
                <div class="reply hide" id="reply-area">
                    <textarea name="reply" id="" placeholder="share your views"></textarea>
                    <input type="submit" name="submit_reply" id="" value="Submit">
                </div>
            </form>
            <div class="topic-reply hide" id="post-replies">

                {% for reply in query.replies.all %}       
                
                <div class="reply-body">
                    <div class="postuser">
                        <div class="user-img">
                            <img src="https://cdn.pixabay.com/photo/2014/04/03/10/32/user-310807_960_720.png">
                        </div>
                        <div class="user-detail">
                            <div class="username"><a href="#">{{ reply.user.username }}</a></div>
                        </div>
                    </div>
                    <div class="content">
                        {{ reply.reply | convert_markdown | safe }}
                        <br>
                    </div>
                </div>

                {% endfor %}
            </div>

        </div>
    {% endblock content %}

templates/forums/search.html
{% extends "forums/base.html" %}
{% load hitcount_tags %}
{% block content %}

    {% if search_box == "title" %}
    
    
        <div class="conatainer">
            <div class="dir">
                <span>Results for :  "{{ searched }}"</span>
            </div>
            <div class="post-table">
                <div class="table-head">
                    <div class="prof-pic">User</div>
                    <div class="subject">Subject</div>
                    <div class="replies">Views<span>/ Replies</span></div>
                    <div class="posted-on">Posted On</div>
                </div>

                {% for obj in objects %}            
                <div class="table-row">
                    <div class="prof-pic"><i class="material-icons">person</i></div>
                    <div class="subject"><a href="{{ obj.get_url }}">{{ obj.title }}</a>
                        <br>
                        <br>
                        <span> Posted by <b><a href="#">{{ obj.user.username }}</a></b></span>
                    </div>
                    <div class="replies">{{ obj.num_rply }} replies | {% get_hit_count for obj %} views</div>
                    <div class="posted-on">{{ obj.date | date }}</div>
                </div>
                {% endfor %}

            </div>
        </div>

    {% elif search_box == "category" %}

        <div class="conatainer">
            <div class="subforum">
                <div class="subforum-title">
                    <h1> Categories</h1>
                </div>

                {% for obj in objects %}      
 
                <div class="subforum-row">
                    <div class="subforum-icon subforum-col col-centre">
                        <i class="material-icons">
                                person
                        </i>
                    </div>
                    <div class="subforum-des subforum-col">
                        <h1><a href="{{ obj.get_url }}">
                        <p> {{obj.title}}</p></a></h1>
                    </div>
                    <div class="subforum-stats subforum-col col-centre">
                        <span>{{ obj.num_queries }} Queries</span>
                    </div>
                    <div class="subforum-info subforum-col">
                        <b><a href="{{obj.last_query.get_url}}">Last Query</a></b> on {{ obj.last_query.date | date }}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
                

    {% endif %}

    <!--Pagination-->
            <div class="pagination">
                Page: {% for num_page in results.paginator.page_range %} <a href="?search-box={{search_box}}&keyword={{searched}}&page={{num_page}}">{{ num_page }}</a>{% endfor %}
            
            </div>            

{% endblock content %}